"""initial schema

Revision ID: 367de70e7ad3
Revises:
Create Date: 2026-10-06 22:11:15.653970

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '367de70e7ad3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_rate_limit_counters',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('normalized_email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_email', name='uq_users_normalized_email')
    )
    op.create_index(op.f('ix_users_normalized_email'), 'users', ['normalized_email'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('benchmark_experiment_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('experiment_scope', sa.String(length=80), nullable=False),
    sa.Column('execution_mode', sa.String(length=40), nullable=False),
    sa.Column('protocol_id', sa.String(length=160), nullable=False),
    sa.Column('protocol_sha256', sa.String(length=64), nullable=False),
    sa.Column('dataset_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('frozen_role_bindings_json', sa.Text(), nullable=False),
    sa.Column('analysis_call_ceiling', sa.Integer(), nullable=False),
    sa.Column('question_generation_call_ceiling', sa.Integer(), nullable=False),
    sa.Column('prompt_generation_call_ceiling', sa.Integer(), nullable=False),
    sa.Column('target_execution_call_ceiling', sa.Integer(), nullable=False),
    sa.Column('judge_call_ceiling', sa.Integer(), nullable=False),
    sa.Column('total_call_ceiling', sa.Integer(), nullable=False),
    sa.Column('reserved_count', sa.Integer(), nullable=False),
    sa.Column('succeeded_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('cancelled_count', sa.Integer(), nullable=False),
    sa.Column('analysis_consumed_count', sa.Integer(), nullable=False),
    sa.Column('question_generation_consumed_count', sa.Integer(), nullable=False),
    sa.Column('prompt_generation_consumed_count', sa.Integer(), nullable=False),
    sa.Column('target_execution_consumed_count', sa.Integer(), nullable=False),
    sa.Column('judge_consumed_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_sequence', sa.Integer(), nullable=False),
    sa.Column('budget_currency', sa.String(length=3), nullable=True),
    sa.Column('max_spend', sa.Float(), nullable=True),
    sa.Column('spent_amount', sa.Float(), nullable=False),
    sa.Column('spent_currency', sa.String(length=3), nullable=True),
    sa.Column('reserved_spend', sa.Float(), nullable=False),
    sa.Column('external_human_approval_verified', sa.Boolean(), nullable=False),
    sa.Column('abort_reason_code', sa.String(length=80), nullable=True),
    sa.Column('failure_reason_code', sa.String(length=80), nullable=True),
    sa.Column('repository_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aborted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('staged', 'running', 'completed', 'failed', 'aborted')", name='ck_benchmark_experiment_runs_status'),
    sa.CheckConstraint('analysis_call_ceiling >= 0 AND question_generation_call_ceiling >= 0 AND prompt_generation_call_ceiling >= 0 AND target_execution_call_ceiling >= 0 AND judge_call_ceiling >= 0 AND total_call_ceiling >= 0', name='ck_benchmark_experiment_runs_nonnegative_ceilings'),
    sa.CheckConstraint('analysis_consumed_count <= analysis_call_ceiling AND question_generation_consumed_count <= question_generation_call_ceiling AND prompt_generation_consumed_count <= prompt_generation_call_ceiling AND target_execution_consumed_count <= target_execution_call_ceiling AND judge_consumed_count <= judge_call_ceiling', name='ck_benchmark_experiment_runs_role_budgets'),
    sa.CheckConstraint('external_human_approval_verified = false', name='ck_benchmark_experiment_runs_human_unverified'),
    sa.CheckConstraint('max_spend IS NULL OR (spent_amount + reserved_spend) <= max_spend', name='ck_benchmark_experiment_runs_spend_reserved_within_limit'),
    sa.CheckConstraint('max_spend IS NULL OR max_spend >= 0', name='ck_benchmark_experiment_runs_max_spend_valid'),
    sa.CheckConstraint('max_spend IS NULL OR spent_amount <= max_spend', name='ck_benchmark_experiment_runs_spend_within_limit'),
    sa.CheckConstraint('reserved_count + succeeded_count + failed_count <= total_call_ceiling', name='ck_benchmark_experiment_runs_total_budget'),
    sa.CheckConstraint('reserved_count >= 0 AND succeeded_count >= 0 AND failed_count >= 0 AND cancelled_count >= 0 AND analysis_consumed_count >= 0 AND question_generation_consumed_count >= 0 AND prompt_generation_consumed_count >= 0 AND target_execution_consumed_count >= 0 AND judge_consumed_count >= 0', name='ck_benchmark_experiment_runs_nonnegative_counts'),
    sa.CheckConstraint('reserved_spend >= 0', name='ck_benchmark_experiment_runs_reserved_spend_nonnegative'),
    sa.CheckConstraint('spent_amount >= 0', name='ck_benchmark_experiment_runs_spend_nonnegative'),
    sa.CheckConstraint('spent_currency IS NULL OR budget_currency IS NULL OR spent_currency = budget_currency', name='ck_benchmark_experiment_runs_spend_currency_match'),
    sa.CheckConstraint('total_call_ceiling = analysis_call_ceiling + question_generation_call_ceiling + prompt_generation_call_ceiling + target_execution_call_ceiling + judge_call_ceiling', name='ck_benchmark_experiment_runs_ceiling_total'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_experiment_runs_dataset_sha256'), 'benchmark_experiment_runs', ['dataset_sha256'], unique=False)
    op.create_index(op.f('ix_benchmark_experiment_runs_owner_id'), 'benchmark_experiment_runs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_benchmark_experiment_runs_protocol_sha256'), 'benchmark_experiment_runs', ['protocol_sha256'], unique=False)
    op.create_index(op.f('ix_benchmark_experiment_runs_status'), 'benchmark_experiment_runs', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('benchmark_provider_call_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_run_id', sa.Uuid(), nullable=False),
    sa.Column('stable_unit_id', sa.String(length=240), nullable=False),
    sa.Column('fixture_id', sa.String(length=160), nullable=False),
    sa.Column('task_id', sa.String(length=160), nullable=False),
    sa.Column('repetition', sa.Integer(), nullable=False),
    sa.Column('provider_role', sa.String(length=40), nullable=False),
    sa.Column('target_condition', sa.String(length=20), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('configured_provider', sa.String(length=120), nullable=False),
    sa.Column('configured_model', sa.String(length=240), nullable=False),
    sa.Column('generation_parameter_sha256', sa.String(length=64), nullable=False),
    sa.Column('request_artifact_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('safe_error_type', sa.String(length=80), nullable=True),
    sa.Column('safe_error_code', sa.String(length=80), nullable=True),
    sa.Column('fallback_classification', sa.String(length=40), nullable=True),
    sa.Column('observation_outcome', sa.String(length=40), nullable=True),
    sa.Column('response_artifact_sha256', sa.String(length=64), nullable=True),
    sa.CheckConstraint("provider_role IN ('analysis', 'question_generation', 'prompt_generation', 'target_execution', 'judge')", name='ck_benchmark_attempts_role'),
    sa.CheckConstraint("status IN ('reserved', 'started', 'succeeded', 'failed', 'cancelled')", name='ck_benchmark_attempts_status'),
    sa.CheckConstraint('cost_estimate IS NULL OR cost_estimate >= 0', name='ck_benchmark_attempts_cost'),
    sa.CheckConstraint('input_tokens IS NULL OR input_tokens >= 0', name='ck_benchmark_attempts_input_tokens'),
    sa.CheckConstraint('output_tokens IS NULL OR output_tokens >= 0', name='ck_benchmark_attempts_output_tokens'),
    sa.CheckConstraint('repetition >= 1', name='ck_benchmark_attempts_repetition'),
    sa.CheckConstraint('total_tokens IS NULL OR total_tokens >= 0', name='ck_benchmark_attempts_total_tokens'),
    sa.ForeignKeyConstraint(['experiment_run_id'], ['benchmark_experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experiment_run_id', 'idempotency_key', name='uq_benchmark_attempts_run_idempotency'),
    sa.UniqueConstraint('experiment_run_id', 'sequence_number', name='uq_benchmark_attempts_run_sequence')
    )
    op.create_index(op.f('ix_benchmark_provider_call_attempts_experiment_run_id'), 'benchmark_provider_call_attempts', ['experiment_run_id'], unique=False)
    op.create_index(op.f('ix_benchmark_provider_call_attempts_provider_role'), 'benchmark_provider_call_attempts', ['provider_role'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members_project_user')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_status'), 'project_members', ['status'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('project_memory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_memory_project_id'), 'project_memory', ['project_id'], unique=False)
    op.create_table('conversation_message_counters',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('processing_version', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'idempotency_key', name='uq_messages_conversation_idempotency'),
    sa.UniqueConstraint('conversation_id', 'sequence', name='uq_messages_conversation_sequence')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('prompt_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('task_category', sa.String(length=40), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('analysis_version', sa.String(length=40), nullable=False),
    sa.Column('analysis_mode', sa.String(length=20), nullable=False),
    sa.Column('ai_provider', sa.String(length=80), nullable=True),
    sa.Column('ai_model', sa.String(length=160), nullable=True),
    sa.Column('ai_succeeded', sa.Boolean(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_analyses_conversation_id'), 'prompt_analyses', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_prompt_analyses_message_id'), 'prompt_analyses', ['message_id'], unique=False)
    op.create_index(op.f('ix_prompt_analyses_project_id'), 'prompt_analyses', ['project_id'], unique=False)
    op.create_index(op.f('ix_prompt_analyses_task_category'), 'prompt_analyses', ['task_category'], unique=False)
    op.create_table('information_gaps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('importance', sa.String(length=20), nullable=False),
    sa.Column('question_target', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['prompt_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_information_gaps_analysis_id'), 'information_gaps', ['analysis_id'], unique=False)
    op.create_table('prompt_analysis_dimensions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applicable', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['prompt_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_analysis_dimensions_analysis_id'), 'prompt_analysis_dimensions', ['analysis_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('source_message_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('original_prompt', sa.Text(), nullable=False),
    sa.Column('optimized_prompt', sa.Text(), nullable=False),
    sa.Column('generation_mode', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['prompt_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_analysis_id'), 'prompt_versions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_prompt_versions_conversation_id'), 'prompt_versions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_prompt_versions_project_id'), 'prompt_versions', ['project_id'], unique=False)
    op.create_index(op.f('ix_prompt_versions_source_message_id'), 'prompt_versions', ['source_message_id'], unique=False)
    op.create_table('question_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('latest_analysis_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stop_reason', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['prompt_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['latest_analysis_id'], ['prompt_analyses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_sessions_analysis_id'), 'question_sessions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_question_sessions_conversation_id'), 'question_sessions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_question_sessions_latest_analysis_id'), 'question_sessions', ['latest_analysis_id'], unique=False)
    op.create_index(op.f('ix_question_sessions_project_id'), 'question_sessions', ['project_id'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_version_id', sa.Uuid(), nullable=True),
    sa.Column('source_message_id', sa.Uuid(), nullable=False),
    sa.Column('execution_strategy', sa.String(length=20), nullable=False),
    sa.Column('optimized_prompt', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('finish_reason', sa.String(length=80), nullable=True),
    sa.Column('usage_json', sa.Text(), nullable=False),
    sa.Column('generation_parameters_json', sa.Text(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_conversation_id'), 'model_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_model_runs_created_at'), 'model_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_model_runs_project_id'), 'model_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_model_runs_prompt_version_id'), 'model_runs', ['prompt_version_id'], unique=False)
    op.create_index(op.f('ix_model_runs_source_message_id'), 'model_runs', ['source_message_id'], unique=False)
    op.create_index(op.f('ix_model_runs_status'), 'model_runs', ['status'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('gap_id', sa.Uuid(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gap_id'], ['information_gaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['question_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_gap_id'), 'questions', ['gap_id'], unique=False)
    op.create_index(op.f('ix_questions_session_id'), 'questions', ['session_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('baseline_model_run_id', sa.Uuid(), nullable=True),
    sa.Column('promptpilot_model_run_id', sa.Uuid(), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('evaluator_provider', sa.String(length=80), nullable=False),
    sa.Column('evaluator_model', sa.String(length=160), nullable=False),
    sa.Column('rubric_version', sa.String(length=40), nullable=False),
    sa.Column('baseline_score', sa.Float(), nullable=True),
    sa.Column('promptpilot_score', sa.Float(), nullable=True),
    sa.Column('overall_delta', sa.Float(), nullable=True),
    sa.Column('winner', sa.String(length=20), nullable=True),
    sa.Column('comparison_summary', sa.Text(), nullable=True),
    sa.Column('baseline_strengths', sa.Text(), nullable=True),
    sa.Column('baseline_weaknesses', sa.Text(), nullable=True),
    sa.Column('promptpilot_strengths', sa.Text(), nullable=True),
    sa.Column('promptpilot_weaknesses', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['baseline_model_run_id'], ['model_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promptpilot_model_run_id'], ['model_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_baseline_model_run_id'), 'evaluations', ['baseline_model_run_id'], unique=False)
    op.create_index(op.f('ix_evaluations_conversation_id'), 'evaluations', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_evaluations_created_at'), 'evaluations', ['created_at'], unique=False)
    op.create_index(op.f('ix_evaluations_project_id'), 'evaluations', ['project_id'], unique=False)
    op.create_index(op.f('ix_evaluations_promptpilot_model_run_id'), 'evaluations', ['promptpilot_model_run_id'], unique=False)
    op.create_table('evaluation_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_id', sa.Uuid(), nullable=False),
    sa.Column('response_label', sa.String(length=20), nullable=False),
    sa.Column('dimension', sa.String(length=40), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'response_label', 'dimension', name='uq_evaluation_items_evaluation_response_dimension')
    )
    op.create_index(op.f('ix_evaluation_items_evaluation_id'), 'evaluation_items', ['evaluation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_items_evaluation_id'), table_name='evaluation_items')
    op.drop_table('evaluation_items')
    op.drop_index(op.f('ix_evaluations_promptpilot_model_run_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_project_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_created_at'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_conversation_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_baseline_model_run_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_session_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_gap_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_model_runs_status'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_source_message_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_prompt_version_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_project_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_created_at'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_conversation_id'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_question_sessions_project_id'), table_name='question_sessions')
    op.drop_index(op.f('ix_question_sessions_latest_analysis_id'), table_name='question_sessions')
    op.drop_index(op.f('ix_question_sessions_conversation_id'), table_name='question_sessions')
    op.drop_index(op.f('ix_question_sessions_analysis_id'), table_name='question_sessions')
    op.drop_table('question_sessions')
    op.drop_index(op.f('ix_prompt_versions_source_message_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_project_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_conversation_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_analysis_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_prompt_analysis_dimensions_analysis_id'), table_name='prompt_analysis_dimensions')
    op.drop_table('prompt_analysis_dimensions')
    op.drop_index(op.f('ix_information_gaps_analysis_id'), table_name='information_gaps')
    op.drop_table('information_gaps')
    op.drop_index(op.f('ix_prompt_analyses_task_category'), table_name='prompt_analyses')
    op.drop_index(op.f('ix_prompt_analyses_project_id'), table_name='prompt_analyses')
    op.drop_index(op.f('ix_prompt_analyses_message_id'), table_name='prompt_analyses')
    op.drop_index(op.f('ix_prompt_analyses_conversation_id'), table_name='prompt_analyses')
    op.drop_table('prompt_analyses')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('conversation_message_counters')
    op.drop_index(op.f('ix_project_memory_project_id'), table_name='project_memory')
    op.drop_table('project_memory')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_status'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_checksum'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_benchmark_provider_call_attempts_provider_role'), table_name='benchmark_provider_call_attempts')
    op.drop_index(op.f('ix_benchmark_provider_call_attempts_experiment_run_id'), table_name='benchmark_provider_call_attempts')
    op.drop_table('benchmark_provider_call_attempts')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_benchmark_experiment_runs_status'), table_name='benchmark_experiment_runs')
    op.drop_index(op.f('ix_benchmark_experiment_runs_protocol_sha256'), table_name='benchmark_experiment_runs')
    op.drop_index(op.f('ix_benchmark_experiment_runs_owner_id'), table_name='benchmark_experiment_runs')
    op.drop_index(op.f('ix_benchmark_experiment_runs_dataset_sha256'), table_name='benchmark_experiment_runs')
    op.drop_table('benchmark_experiment_runs')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_normalized_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('auth_rate_limit_counters')
    # ### end Alembic commands ###
